# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:16 # ใช้ PostgreSQL เวอร์ชัน 16
    container_name: facebook-clone-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: facebook-clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: